version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
